[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Credentials = "true"

[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  framework = "vite"